### ISSUE TITLE
VFD Parameters

### ISSUE THREAD

**Issue by Glennien** [ModuloFS/LCNC_RatRig_KillerBee#1]
Is there any way you could publish the VFD parameters you have changed? Your config has been a great help, but I'm having issues with getting the communications to work.

Great work by the way, thanks!

**Comment by ModuloFS** [comment]
Hello,

which VFD you are using? 

The config is made for a Folinn H1 or clones from stepperonline for example. 
Communication should be possible without any modification of the parameters, just the correct control of the VFD is not possible in inital status. 

The most importand parameter is P01.47 which has to be set to 1 because you are only able to send 16 bit values and because of that it is not possible in inital status to set the output speed to 100 %. I will take a look later in my configurations of the VFD if i have it to hand.

**Comment by Glennien** [comment]
Greetings, and thanks for your reply.

I am using a Folinn H1 series. The exact driver number is "H110S20022BX0". It has the H101 card installed.
I have set the (start, fwd etc) sources to the correct parameters.

I have attempted communication via VFDMod, aswell as with a standalone modbus client (QModBus), and I am receiving the same error, regardless if using VFDMod or QModBus.
I have attempted a few different baud rates, aswell as different communication delays - to no effect.

I am starting to wonder if there is an issue in my VFD comms.
The issue I am having is:
The VFD does not have the correct slave address, and therefore my clients will ignore it. I am sure the parameter for address is set correct, but I can not figure this out. I have been going at it for some time now, and about to give up and change to analog control.

Do you know which "expansion" card is installed in your VFD?

**Comment by ModuloFS** [comment]
I have the simple version  with the H100 panel and the type code "H100S20022BX0". 
Do you have checked your wiring of the RS485? I see, there is a jumper on your board for the RS485 communication, do you have set it correct? 
Your problem sounds more hardware related than software.

**Comment by Glennien** [comment]
Yeah, mine is also the "Standard card" (H0100 / H0101), with 4 DI, 1 channel analog, 1 relay output. Not sure why the part number (on the drive itself) is different from yours, seing as we have the same control board installed.

The only jumper I have available is switching between 0-10v and 4-20ma.
I'm guessing there might be wrong firmware on my drive, or similar. I can't seem to chase this down.

Thanks for your help so far, atleast you've helped me narrow it down a little bit.
Cheers

**Comment by Glennien** [comment]
Closing issue, as the problem is not related to this configuration. I will report back if I figure out what is wrong incase anybody else should encouter this.
